import { useMemo, useState } from 'react'
import { AlertTriangle, BellRing, CheckCircle2, ChevronRight, Clock3, ListChecks, Search, UserRound, UsersRound, X } from 'lucide-react'
import { api } from '../lib/api'
import type { AppUser, MissionTask } from '../types'

export function LeaderHome({ user, users, tasks, focus = 'overview', onOpenTask, onRemind }: { user: AppUser; users: AppUser[]; tasks: MissionTask[]; focus?: 'overview' | 'tasks' | 'squad'; onOpenTask: (task: MissionTask) => void; onRemind: () => void }) {
  const squadMembers = useMemo(() => users.filter((u) => u.role === 'soldier' && u.squad === user.squad), [users, user.squad])
  const completed = squadMembers.filter((s) => (s.completionRate || 0) >= 80).length
  const percent = squadMembers.length ? Math.round(squadMembers.reduce((sum, s) => sum + (s.completionRate || 0), 0) / squadMembers.length) : 0
  const [filter, setFilter] = useState<'all' | 'done' | 'waiting'>('all')
  const [selected, setSelected] = useState<AppUser | null>(null)
  const [query, setQuery] = useState('')
  const filtered = useMemo(() => squadMembers.filter((s) => (filter === 'all' || (filter === 'done' ? (s.completionRate || 0) >= 80 : (s.completionRate || 0) < 80)) && `${s.name} ${s.username}`.toLowerCase().includes(query.toLowerCase())), [filter, squadMembers, query])

  if (focus === 'tasks') return <div className="page-stack"><section className="hero-card leader-hero"><div className="hero-badge"><ListChecks size={16}/> NHIỆM VỤ ĐƠN VỊ</div><div className="hero-title">{user.squad}</div><div className="hero-subtitle">{tasks.length} lệnh tác nghiệp được triển khai</div></section><div className="task-list compact-six-list compact-six-leader-tasks">{tasks.map((task) => <button className="leader-task-row" key={task.id} type="button" onClick={() => onOpenTask(task)}><div className="mission-code">{task.code?.slice(-3) || task.id}</div><div><strong>{task.title}</strong><span>{task.deadline} · {task.completedCount}/{task.totalCount}</span></div><ChevronRight size={16}/></button>)}</div></div>

  return <div className="page-stack">
    <section className="hero-card leader-hero"><div className="hero-badge"><UsersRound size={16}/> {user.squad}</div><div className="hero-title">{focus === 'squad' ? 'Quân số tiểu đội' : 'Tiến độ triển khai'}</div><div className="big-number-row"><strong>{percent}%</strong><span>{completed}/{squadMembers.length} chiến sĩ đạt tiến độ</span></div><div className="hero-progress"><span style={{ width: `${percent}%` }}/></div></section>
    <section className="quick-grid"><button className={`quick-card ${filter === 'done' ? 'selected' : ''}`} type="button" onClick={() => setFilter('done')}><CheckCircle2 size={19}/><strong>{completed}</strong><span>Đạt tiến độ</span></button><button className={`quick-card ${filter === 'waiting' ? 'selected' : ''}`} type="button" onClick={() => setFilter('waiting')}><Clock3 size={19}/><strong>{Math.max(squadMembers.length - completed, 0)}</strong><span>Cần nhắc</span></button><button className="quick-card" type="button" onClick={onRemind}><BellRing size={19}/><strong>{tasks.filter((t) => t.status !== 'completed').length}</strong><span>Lệnh đang chạy</span></button></section>
    <div className="search-command compact"><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm chiến sĩ..."/></div>
    <section className="section-block"><div className="section-heading"><div><span className="section-kicker">{user.squad.toUpperCase()}</span><h2>Danh sách chiến sĩ</h2></div><button className="ghost-link" type="button" onClick={() => setFilter('all')}>Tất cả <ChevronRight size={16}/></button></div><div className="member-list compact-six-list compact-six-members">{filtered.map((s) => <button className="member-row member-row-button" type="button" key={s.id} onClick={() => setSelected(s)}><div className="avatar">{s.name.slice(-1)}</div><div className="member-info"><strong>{s.name}</strong><span>@{s.username} · hoạt động {s.lastSeen}</span></div><span className={(s.completionRate || 0) >= 80 ? 'member-state done' : 'member-state waiting'}>{s.completionRate ?? 0}%</span><ChevronRight size={14}/></button>)}</div></section>
    <button className="secondary-action" type="button" onClick={onRemind}><AlertTriangle size={16}/> NHẮC NHỮNG NGƯỜI CHƯA ĐẠT TIẾN ĐỘ</button>
    {selected && <div className="dialog-backdrop" onMouseDown={() => setSelected(null)}><section className="center-form-modal soldier-profile-modal" onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><div><span className="military-kicker">HỒ SƠ CHIẾN SĨ</span><h3>{selected.name}</h3></div><button className="dialog-close" type="button" onClick={() => setSelected(null)}><X size={17}/></button></div><div className="soldier-profile-rank"><div className={`account-avatar soldier ${selected.avatarUrl ? 'has-photo' : ''}`}>{selected.avatarUrl ? <img src={api.resolveAsset(selected.avatarUrl)} alt={selected.name}/> : <UserRound size={17}/>}</div><div><strong>{selected.rank || 'Chiến sĩ'}</strong><span>{selected.squad}</span></div></div><div className="account-detail-grid"><div><span>NHIỆM VỤ</span><strong>{selected.completedMissions ?? 0}</strong></div><div><span>TỶ LỆ</span><strong>{selected.completionRate ?? 0}%</strong></div><div><span>TRẠNG THÁI</span><strong>{selected.active ? 'TRỰC TUYẾN' : 'KHÓA'}</strong></div><div><span>HOẠT ĐỘNG</span><strong>{selected.lastSeen || '—'}</strong></div></div></section></div>}
  </div>
}
